### PR TITLE
Fix incorrect conditional check in common prefix function

### PR DESCRIPTION
**Pull request by afterdusk**

### CODE REVIEW

**Review by eozturk1 — COMMENTED** [review]
Can we add a test with previously failing values?

**Comment by slawlor** [comment]
Great catch, also want to have @kevinlewi look this over!

**Comment by kevinlewi** [comment]
Amazing.

**Comment by afterdusk** [comment]
Added tests that would have failed prior to this fix

**Review by slawlor — APPROVED** [review]
LGTM!

**Review by eozturk1 — APPROVED** [review]

**Pull request merged**
